services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    container_name: product-updates-reprocessor-azurite
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - product_updates_reprocessor_azurite_data:/data

volumes:
  product_updates_reprocessor_azurite_data:
